name: 🎯 Publishing Checklist
description: Final checklist before publishing a website
labels: []
body:
  - type: checkboxes
    id: title
    attributes:
      label: Meta tags
      description: Are all meta tags present and displaying the correct information in the server rendered source?
      options:
        - label: Site title, meta title
        - label: Meta description, OG description
        - label: Meta thumbnail, OG image
        - label: OG video
  - type: checkboxes
    id: favicon
    attributes:
      label: Favicon
      description: Is the favicon available in all necessary formats and are the neccessary meta tags present?
      options:
        - label: favicon.svg
        - label: favicon.ico
        - label: apple-touch-icon-180x180.png
        - label: icon-192x192.png
        - label: icon-512x512.png
        - label: manifest.webmanifest
        - label: Meta tags added to the `<head>`
  
